### ISSUE TITLE
Non-fatal errors in Moodle 3.6.3+

### ISSUE THREAD

**Issue by dnsturrock** [YourAcclaim/block_acclaim#1]
Non-fatal errors showing for youracclaim block in Moodle 3.6.3+ when debugging set to "Developer".
**When adding the block to a course.**
Error displays in header: 
<b>Warning</b>: Creating default object from empty value in <b> 
<file path>/blocks/acclaim/block_acclaim.php</b> on line <b>51</b><br />
![image](https://user-images.githubusercontent.com/51100509/58443650-5fb6fe00-8147-11e9-87e6-1dd62741abb9.png)

**When configuring a block.**

Error displays in header: 
<div class="notifytiny debuggingmessage" data-rel="debugging">Did you remember to call setType() for 'blockid'? Defaulting to PARAM_RAW cleaning.<ul style="text-align: left" data-rel="backtrace"><li>line 1354 of /lib/formslib.php: call to debugging()</li><li>line 312 of /lib/formslib.php: call to moodleform->detectMissingSetType()</li><li>line 218 of /lib/formslib.php: call to moodleform->_process_submission()</li><li>line 52 of /blocks/acclaim/view.php: call to moodleform->__construct()</li></ul></div><div class="notifytiny debuggingmessage" data-rel="debugging">Did you remember to call setType() for 'courseid'? Defaulting to PARAM_RAW cleaning.<ul style="text-align: left" data-rel="backtrace"><li>line 1354 of /lib/formslib.php: call to debugging()</li><li>line 312 of /lib/formslib.php: call to moodleform->detectMissingSetType()</li><li>line 218 of /lib/formslib.php: call to moodleform->_process_submission()</li><li>line 52 of /blocks/acclaim/view.php: call to moodleform->__construct()</li></ul></div><div class="notifytiny debuggingmessage" data-rel="debugging">Did you remember to call setType() for 'badgename'? Defaulting to PARAM_RAW cleaning.<ul style="text-align: left" data-rel="backtrace"><li>line 1354 of /lib/formslib.php: call to debugging()</li><li>line 312 of /lib/formslib.php: call to moodleform->detectMissingSetType()</li><li>line 218 of /lib/formslib.php: call to moodleform->_process_submission()</li><li>line 52 of /blocks/acclaim/view.php: call to moodleform->__construct()</li></ul></div>

![image](https://user-images.githubusercontent.com/51100509/58443694-b45a7900-8147-11e9-8f1e-89c6171f4f69.png)

**When viewing a course which has had a youracclaim block added.**
Error displays in header: 
<b>Warning</b>: Creating default object from empty value in <b> 
<file path>/blocks/acclaim/block_acclaim.php</b> on line <b>51</b><br />

**Comment by yancyribbens** [comment]
@dnsturrock thanks for reporting this.  I've tagged this as a future enhancement.
