### ISSUE TITLE
enum_badges.php open proxy

### ISSUE THREAD

**Issue by danmarsden** [YourAcclaim/block_acclaim#12]
the enum_badges.php file doesn't appear to be used, but looks very close to providing a possible open proxy - I'd suggest removing this completely, however if it is required you would need to implement some better security around the url, require login etc etc.

**Comment by zioth** [comment]
I don't see this file anywhere in the current version of the plugin, and I don't see any other potential open proxies. Closing the ticket, but feel free to reopen if you think I missed anything.
