### ISSUE TITLE
Retain selected badge on course backup/restore

### ISSUE THREAD

**Issue by dnsturrock** [YourAcclaim/block_acclaim#2]
When restoring a backup of a Moodle course,  the youracclaim block loses any reference to the badge selected in the original course. Same issue occurs when importing course content, including blocks, into a separate course.

Replicated on Moodle 3.3, 3.5 and 3.6. When making a backup, all options to retain course data were retained except for course logs.

**Comment by yancyribbens** [comment]
@dnsturrock thanks for reporting this.  It sounds like the workaround is to reselect the badges for each course after restoring each time?

**Comment by zioth** [comment]
Fixed
