### ISSUE TITLE
Core moodle 3.6 unit tests failing Unexpected debugging() call detected

### ISSUE THREAD

**Issue by kristian-94** [YourAcclaim/block_acclaim#28]
The acclaim block's unit tests pass, but the plugin makes other core moodle unit tests fail. 

1. Install plugin into a clean moodle 3.6
2. php admin/tool/phpunit/cli/init.php
3. `vendor/bin/phpunit "restore_stepslib_date_testcase" backup/moodle2/tests/restore_stepslib_date_test.php`
You will see the following error: 

> There was 1 error:
> 
> 1) restore_stepslib_date_testcase::test_course_completion_date_restore
> Unexpected debugging() call detected.
> Debugging: Exception encountered in event observer '\block_acclaim\group_observers::block_acclaim_issue_badge': Can't find data record in database table block_acclaim. (SELECT * FROM {block_acclaim} WHERE courseid = ?
> [array (
>   0 => '140000',
> )])
> * line 1538 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
> * line 69 of /blocks/acclaim/lib.php: call to moodle_database->get_record()
> * line 34 of /blocks/acclaim/classes/group_observers.php: call to block_acclaim_get_block_course()
> * line ? of unknownfile: call to block_acclaim\group_observers::block_acclaim_issue_badge()
> * line 155 of /lib/classes/event/manager.php: call to call_user_func()
> * line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
> * line 834 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
> * line 173 of /completion/completion_completion.php: call to core\event\base->trigger()
> * line 223 of /backup/moodle2/tests/restore_stepslib_date_test.php: call to completion_completion->mark_complete()
> * line ? of unknownfile: call to restore_stepslib_date_testcase->test_course_completion_date_restore()
> * line 1071 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to ReflectionMethod->invokeArgs()
> * line 939 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestCase->runTest()
> * line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit\Framework\TestCase->runBare()
> * line 698 of /vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
> * line 894 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestResult->run()
> * line 755 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestCase->run()
> * line 545 of /vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit\Framework\TestSuite->run()
> * line 195 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\TestRunner->doRun()
> * line 148 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\Command->run()
> * line 53 of /vendor/phpunit/phpunit/phpunit: call to PHPUnit\TextUI\Command::main()
> 
> 
> /siteroot/lib/phpunit/classes/advanced_testcase.php:88
> 
> To re-run:
>  vendor/bin/phpunit "restore_stepslib_date_testcase" backup/moodle2/tests/restore_stepslib_date_test.php

We also see the unexpected debugging call in 4 other places in core tests that call mark_complete()
We don't have anything in the block_acclaim table during other core tests.

**Comment by danmarsden** [comment]
I saw this when looking at issue #13 too but doesn't look like I recorded that - I understand a fix for issue #13 might be underway which might also address this at the same time.

**Comment by danmarsden** [comment]
FYI - here's a patch I added to our clients site that addresses this particular unit test failure. I probably should have filed a pull request with this change - sorry!

```
Author: Dan Marsden <dan@danmarsden.com>
Date:   Thu Aug 1 12:53:23 2019 +1200

    Fix unit test failure until acclaim separate out the events.

diff --git a/blocks/acclaim/classes/group_observers.php b/blocks/acclaim/classes/group_observers.php
index 29174599489..3f98702f9ac 100755
--- a/blocks/acclaim/classes/group_observers.php
+++ b/blocks/acclaim/classes/group_observers.php
@@ -32,6 +32,10 @@ class group_observers {
     {
         global $DB;
         $course = block_acclaim_get_block_course($event->courseid);
+        if (empty($course)) {
+            // No acclaim block found in this course.
+            return;
+        }
         $expires_timestamp = "";
         
         if($course->expiration){
diff --git a/blocks/acclaim/lib.php b/blocks/acclaim/lib.php
index e46d84d3863..2b9031866db 100755
--- a/blocks/acclaim/lib.php
+++ b/blocks/acclaim/lib.php
@@ -66,7 +66,7 @@ function block_acclaim_get_badge_info($course_id,$field)
 function block_acclaim_get_block_course($course_id)
 {
     global $DB;
-    $course = $DB->get_record('block_acclaim', array('courseid' => $course_id), '*', MUST_EXIST);
+    $course = $DB->get_record('block_acclaim', array('courseid' => $course_id), '*');
     return $course;
 }

**Comment by danmarsden** [comment]
although - I should mention - that wrapper function is really unecessary and adds complexity where it isn't required.

it would be better to replace:
$course = block_acclaim_get_block_course($event->courseid);
with a simple call to:
$course = $DB->get_record('block_acclaim', array('courseid' => $event->courseid), '*');

calling the normal Moodle API inline - rather than wrapping an api call in a custom function name.

**Comment by zioth** [comment]
Thank you for digging into this. A fix will be in the next release.

**Comment by zioth** [comment]
Fixed
