### ISSUE TITLE
Can date expiry be set to a fixed date range from now into the future?

### ISSUE THREAD

**Issue by swinster** [YourAcclaim/block_acclaim#29]
Feature Request:

Our Acclaim badges are issued to expire 2 years from the date of earning. It looks as if the current implementation of the plugin can only set an expiry at a fixed date in the future, meaning that we will need to manually edit all automatically issued badges which kinda defeats the purpose. It would be good to indicate the expiry date in the block once saved.

In addition (and possibly this needs to be a separate issue), after setting the expiry date then exiting and re-enter the "select badge" settings in the block, it appears as if no date was ever set (i.e. the checkbox is not checked and the date has returned to `now`). Further, when re-entering the "select badge" settings in the block, the actual badge that was set reverts to the top one in the list.

**Comment by swinster** [comment]
Any updates here? This would really help our badge issuance with Acclaim.

**Comment by swinster** [comment]
Any updates? Relative dates are now a thing in Moodle, and without Acclaim being able to use them, it make the issuance and management or eLearning badges almost impossible.

**Comment by swinster** [comment]
I wonder if anyone from Acclaim is reading these?

**Comment by zioth** [comment]
Sorry for the delay in responding. It may be some time before we get to this feature request, but a batch of bug fixes is on its way. Thank you for your suggestion. I agree that it would be a useful feature.

**Comment by swinster** [comment]
Hi @zioth thank you for the feedback. I see the progress which is going on here which is awesome, although this is a blocker for us in being able to use this integration. Without a way to expire the badge on issue, I can create re-engagement in the module. I look forward to your further progress with interest.

**Comment by zioth** [comment]
If you represent a current Acclaim customer, you should consider going through customer support channels. They'd probably be interested to know about your interest in the Moodle integration, and they can work with you on prioritizing this feature request.

**Comment by swinster** [comment]
I did they said this was the best place to go :|

On 14 May 2020 21:10, Zioth <notifications@github.com> wrote:

If you represent a current Acclaim customer, you should consider going through customer support channels. They'd probably be interested to know about your interest in the Moodle integration, and they can work with you on prioritizing this feature request.

**Comment by zioth** [comment]
That's funny. Sorry for the miscommunication.

I'll contact the right people to figure out the status of your request. Could you tell me which company you represent? A private message would be fine if you don't want it in your public GitHub history.

**Comment by swinster** [comment]
HI, Its fine Pexip is the company.

On 14 May 2020 22:34, Zioth <notifications@github.com> wrote:

That's funny. Sorry for the miscommunication.

I'll contact the right people to figure out the status of your request. Could you tell me which company you represent? A private message would be fine if you don't want it in your public GitHub history.

**Comment by zioth** [comment]
Thank you. I've brought it to the attention of the right people. No guarantees as to timing, but we're aware of the request now.

**Comment by zioth** [comment]
We've decided not to implement this feature. However, a new feature is in the works which will allow badge templates to be created on the Acclaim platform with automatic expiration X days after issuance. When it's available, you will be able to create templates that expire after two years, and ignore the expiration feature of the Moodle plugin.

If you're subscribed to the Acclaim newsletter, you should get an update when this feature is deployed.

**Comment by swinster** [comment]
Thanks @zioth and understood. Actually this a very clever interpretation of these requirements which seems like it would cover more options for both you and us. Look forward to it coming live.
