### ISSUE TITLE
Configure Acclaim Block leads to an internal server error

### ISSUE THREAD

**Issue by swinster** [YourAcclaim/block_acclaim#30]
Hi,

We have just setup the Acclaim plugin and running some basic tests. With editing on in a course, you see the block settings and an option to "Configure Acclaim Block". Unfortunately, clicking this leads to a 500 Internal Server Error response. 

![image](https://user-images.githubusercontent.com/8142964/67153085-46bc0e80-f2db-11e9-8c9f-0284592bb6c4.png)

**Comment by swinster** [comment]
Any updates on this one?

**Comment by zioth** [comment]
A few questions:

1. What version of Moodle are you running?
2. Did anything show up in the logs? Moodle typically logs errors to the Apache error log.
3. Where did the 500 error show up? Was the whole Moodle UI replaced with the error?

**Comment by zioth** [comment]
No response in 20 days, so I'm closing this ticket. If you see the issue again, feel free to reopen.
