### ISSUE TITLE
lang string missing for acclaim:editbadge

### ISSUE THREAD

**Issue by guillogo** [YourAcclaim/block_acclaim#39]
Hi,

With the latest version of the plugin, if you want to edit a role /admin/roles/define.php?action=edit&roleid=XX

You will get a warning before the list of capabilities:

```
Invalid get_string() identifier: 'acclaim:editbadge' or component 'block_acclaim'. Perhaps you are missing $string['acclaim:editbadge'] = ''; in /var/www/site/blocks/acclaim/lang/en/block_acclaim.php?

    line 353 of /lib/classes/string_manager_standard.php: call to debugging()
    line 7309 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
    line 2667 of /lib/accesslib.php: call to get_string()
    line 2512 of /lib/accesslib.php: call to get_capability_string()
    line 118 of /admin/roles/classes/capability_table_base.php: call to get_capability_docs_link()
    line 135 of /admin/roles/classes/capability_table_with_risks.php: call to core_role_capability_table_base->display()
    line 678 of /admin/roles/classes/define_role_table_advanced.php: call to core_role_capability_table_with_risks->display()
    line 268 of /admin/roles/define.php: call to core_role_define_role_table_advanced->display()
```
We need to add this lang string

Thank you.

**Comment by zioth** [comment]
I don't see that warning for any of the roles on my system. Which role are you looking at? Could you include a screenshot of the page?

**Comment by guillogo** [comment]
It happens with editing any role 

![Selection_003](https://user-images.githubusercontent.com/6785838/83593869-1d699d80-a5a1-11ea-96d0-47743b31a69f.png)

![Selection_004](https://user-images.githubusercontent.com/6785838/83594007-69b4dd80-a5a1-11ea-8ef3-b525d0814318.png)

**Comment by zioth** [comment]
Thank you for catching this bug. It is now fixed.
