### ISSUE TITLE
IDE config files and zip file should be removed

### ISSUE THREAD

**Issue by danmarsden** [YourAcclaim/block_acclaim#4]
Hi there, 

We've been asked by one of our clients to take a look at this plugin - as part of this review I will try to make it clear which issues are also likely to block approval in the official moodle.org plugins database.

Tthe acclaim.zip file seems to be an old zip of the acclaim codebase (including a git folder) - this should be removed from the code.

Also the .settings folder, .buildpath, and .project files should really be removed - these are IDE specific files and it might be worth configuring your .gitignore to ignore these.

**Comment by yancyribbens** [comment]
@danmarsden this has been addressed here https://github.com/YourAcclaim/block_acclaim/pull/17

**Comment by yancyribbens** [comment]
merged https://github.com/YourAcclaim/block_acclaim/pull/17
