### ISSUE TITLE
get_string call in block_acclaim.php is not pointing at correct module and string identifier

### ISSUE THREAD

**Issue by kristian-94** [YourAcclaim/block_acclaim#42]
In this code here: https://github.com/YourAcclaim/block_acclaim/blob/master/block_acclaim.php#L101

We see `get_string('acclaim', 'no_badge');` , which is wrong. 

In moodle the get string function is like this: `get_string($identifier, $component = '', ...)` it takes an identifier and then a component.

For this string it needs to be  `get_string('no_badge', 'block_acclaim');`

**Comment by zioth** [comment]
Fixed by the reporter. Thanks!
