### ISSUE TITLE
Is this the official Credly plugin for Moodle?

### ISSUE THREAD

**Issue by Zyten** [YourAcclaim/block_acclaim#47]
Someone implied as such in a different Credly plugin:
https://github.com/MMDevelopment/moodle-block_credly/issues/6
https://github.com/MMDevelopment/moodle-block_credly/issues/8

but I don't see this plugin claiming so, nor is it mentioned in the Credly website.
In either case, please add a label in the Readme to specify if it's official/unofficial

**Comment by tylersp7** [comment]
Hello, this is the official Credly plugin, we normally send it out to organizations that specify an interest in using our Moodle plugin as it requires additional information and won't work without that setup.  Thank you!
