### ISSUE TITLE
New version 2023010900 is missing some table column creation scripts 

### ISSUE THREAD

**Issue by srijayasinghe84** [YourAcclaim/block_acclaim#50]
In upgrade.php file new table column creation scripts are missing. It'll not crate new table column "badgeurl" in "mdl_block_acclaim_courses" table.

**Comment by ahripak** [comment]
Hi @srijayasinghe84! We've included updates that should address that issue in the latest release here: https://github.com/YourAcclaim/block_acclaim/releases/tag/release%2F2024040800
