### ISSUE TITLE
Missing field badgeurl in db/upgrade.php

### ISSUE THREAD

**Issue by ScottVerbeek** [YourAcclaim/block_acclaim#53]
Commit  Update Moodle Verbiage to Credly [IN-881] (12d6d4c16e0574d06be7b2f5313d1102aafc3b41) does not contain upgrade steps for introducing the column badgeurl. 

The field was added to the table `block_acclaim_courses`.
```xml
        <FIELD NAME="badgeurl" TYPE="text" NOTNULL="true" SEQUENCE="false" COMMENT="Badge URL"/>
```

This field must be added to `db/upgrade.php`.

[IN-881]: https://wfspearson.atlassian.net/browse/IN-881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ahripak** [comment]
Hi @ScottVerbeek! Thank for you for your contribution here. We've included the changes in the latest release here: https://github.com/YourAcclaim/block_acclaim/releases/tag/release%2F2024040800
