### ISSUE TITLE
Need to test the plugin for Moodle4.1

### ISSUE THREAD

**Issue by digvijayll** [YourAcclaim/block_acclaim#55]
I want to use this plugin for Moodle4.1
But before that I want to make sure that this plugin is compatible for Moodle4.1 and  test the functionality of the plugin also. But it is asking for some credentials as shown below :

![Screenshot from 2024-05-15 18-11-10](https://github.com/YourAcclaim/block_acclaim/assets/169907387/0d34184f-4538-4acc-95cd-edea93525cb8)

I don't know where to get the credentials for testing only. And without the credentials the block is giving error when I click on "Select badge".

It will be a great help if anyone knows if it is compatible with Moodle4.1 or where to get the test credentials for testing.

**Comment by ahripak** [comment]
Hi @digvijayll!

You would obtain the Credly Organization ID and Credly App Token from the Credly platform signed in as an administrator of an organization. If you have a current contract with Credly you should be able to reach out to your Customer Success Manager or Account Manager and they can help guide you through the process.

**Comment by digvijayll** [comment]
Thanks @ahripak for this fast reply !

But I don't have any contract with Credly. Is it possible to test this plugin without having any contract with credly?
And can you please tell one more thing... Is it compatible with 4.1 version of Moodle?

Thanks again for the help.

**Comment by ahripak** [comment]
> But I don't have any contract with Credly. Is it possible to test this plugin without having any contract with credly?

Possibly! I would recommend writing into https://info.credly.com/schedule-a-demo, they may be able to help get you access to a test account on Sandbox (Credly's integration testing environment)

>  Is it compatible with 4.1 version of Moodle?

Yes, it is compatible with Moodle 4.1

**Comment by digvijayll** [comment]
Thanks @ahripak ! I really appreciate your help.
