### ISSUE TITLE
Missing privacy API

### ISSUE THREAD

**Issue by danmarsden** [YourAcclaim/block_acclaim#6]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data.

Sites that use continuous integration processes (like us) will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

Please note - This does block our client from using the plugin due to our CI processes, but it is not currently a blocker for approval in the plugins db, although compliance with the privacy api may become a blocker in future.

**Comment by yancyribbens** [comment]
@danmarsden thanks for the notification.  A PR to implement the privacy provider is [here](https://github.com/YourAcclaim/block_acclaim/pull/19)
