### ISSUE TITLE
functions and classes must be namespaced or prefixed

### ISSUE THREAD

**Issue by danmarsden** [YourAcclaim/block_acclaim#7]
All functions within a plugin should either be namespaced within block_acclaim or prefixed with the plugin name "block_acclaim"

for example:
https://github.com/YourAcclaim/block_acclaim/blob/master/lib.php

function truncate() should be: function block_acclaim_truncate()
function get_badge_info should be block_acclaim_get_badge_info()
function get_block_course() should be block_acclaim_get_block_course()

class acclaim_form should be class block_acclaim_form (or namespaced in the classes folder)

**Comment by yancyribbens** [comment]
@danmarsden created a [PR](https://github.com/YourAcclaim/block_acclaim/pull/16) and will close this issue if the PR looks good.

**Comment by yancyribbens** [comment]
merged https://github.com/YourAcclaim/block_acclaim/pull/16
